# Generated by Django 2.0.1 on 2018-03-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(max_length=100)),
                ('good_img', models.ImageField(upload_to='')),
                ('good_category', models.ForeignKey(on_delete='CASCADE', to='books.Category')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_number', models.CharField(max_length=50)),
                ('user_pwd', models.CharField(max_length=50)),
                ('user_stars', models.FloatField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='good_owener',
            field=models.ForeignKey(on_delete='CASCADE', to='books.UserInfo'),
        ),
    ]
