# Generated by Django 2.0.1 on 2018-03-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='good_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
