# Generated by Django 2.0.1 on 2018-03-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_user_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='good_img_2nd',
            field=models.ImageField(null=True, upload_to='upload_imgs'),
        ),
        migrations.AddField(
            model_name='goods',
            name='good_img_3rd',
            field=models.ImageField(null=True, upload_to='upload_imgs'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_stars',
            field=models.FloatField(default=5, null=True),
        ),
    ]
