# Generated by Django 2.0.1 on 2018-03-27 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20180325_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='caption',
            field=models.CharField(max_length=30, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='good_context',
            field=models.CharField(max_length=300, null=True, verbose_name='详细信息'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='good_img',
            field=models.ImageField(upload_to='upload_imgs', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='good_img_2nd',
            field=models.ImageField(null=True, upload_to='upload_imgs', verbose_name='图片(可选)'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='good_img_3rd',
            field=models.ImageField(null=True, upload_to='upload_imgs', verbose_name='图片(可选)'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='good_name',
            field=models.CharField(max_length=100, verbose_name='书名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_info',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_number',
            field=models.CharField(max_length=50, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_stars',
            field=models.FloatField(default=5, null=True, verbose_name='用户等级(默认为5)'),
        ),
    ]
