# Generated by Django 2.0.1 on 2018-03-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_goods_good_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='good_img',
            field=models.ImageField(default=None, upload_to='upload_imgs/'),
        ),
    ]
