# Generated by Django 2.0.1 on 2018-03-27 04:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20180327_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='good_category',
            field=models.ForeignKey(on_delete='CASCADE', to='books.Category', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='good_img_2nd',
            field=models.ImageField(blank=True, null=True, upload_to='upload_imgs', verbose_name='图片(可选)'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='good_img_3rd',
            field=models.ImageField(blank=True, null=True, upload_to='upload_imgs', verbose_name='图片(可选)'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='good_owener',
            field=models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL, verbose_name='拥有者'),
        ),
    ]
