# Generated by Django 2.0.1 on 2018-03-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20180318_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='good_img',
            field=models.ImageField(default='upload_imgs/default.jpg', upload_to='upload_imgs/'),
        ),
    ]
