# Generated by Django 2.0.1 on 2018-03-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20180318_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='good_img',
            field=models.ImageField(blank=True, null=True, upload_to='upload_imgs/'),
        ),
    ]
