# Generated by Django 2.0.1 on 2018-03-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20180318_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='good_img',
            field=models.ImageField(default=1, upload_to='upload_imgs/'),
            preserve_default=False,
        ),
    ]
