# Generated by Django 2.0.4 on 2018-04-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20180408_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_info',
            field=models.CharField(default=123442535, max_length=100, verbose_name='联系方式'),
            preserve_default=False,
        ),
    ]
