# Generated by Django 2.0.1 on 2018-03-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20180318_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='good_img',
            field=models.ImageField(upload_to=' books/static/books/upload_imgs'),
        ),
    ]
