# Generated by Django 2.0.1 on 2018-03-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20180318_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='good_img',
            field=models.ImageField(upload_to='upload_imgs'),
        ),
    ]
